const data = [
  {
    class: "crossfit",
    day: "Monday",
    startTime: "10:00",
    endTime: "14:00",
  },
  {
    class: "launge ball",
    day: "Monday",
    startTime: "16:00",
    endTime: "18:00",
  },
  {
    class: "walls",
    day: "Monday",
    startTime: "18:00",
    endTime: "20:00",
  },
  {
    class: "launge ball",
    day: "Monday",
    startTime: "21:00",
    endTime: "23:00",
  },
  {
    class: "launge ball",
    day: "Tuesday",
    startTime: "14:00",
    endTime: "17:00",
  },
  {
    class: "ppsr",
    day: "Tuesday",
    startTime: "18:00",
    endTime: "20:00",
  },
  {
    class: "walls",
    day: "Tuesday",
    startTime: "20:00",
    endTime: "22:00",
  },
  {
    class: "crossfit",
    day: "Wednesday",
    startTime: "10:00",
    endTime: "15:00",
  },
  {
    class: "candy",
    day: "Wednesday",
    startTime: "16:00",
    endTime: "19:00",
  },
  {
    class: "walls",
    day: "Wednesday",
    startTime: "20:30",
    endTime: "23:00",
  },
  {
    class: "crossfit",
    day: "Thursday",
    startTime: "14:00",
    endTime: "17:00",
  },
  {
    class: "chelsea",
    day: "Thursday",
    startTime: "18:00",
    endTime: "22:00",
  },
  {
    class: "chelsea",
    day: "Thursday",
    startTime: "18:00",
    endTime: "22:00",
  },
  {
    class: "launge ball",
    day: "Friday",
    startTime: "10:00",
    endTime: "13:00",
  },
  {
    class: "candy",
    day: "Friday",
    startTime: "16:00",
    endTime: "19:00",
  },
  {
    class: "crossfit",
    day: "Friday",
    startTime: "22:00",
    endTime: "23:00",
  },
  {
    class: "walls",
    day: "Saturday",
    startTime: "14:00",
    endTime: "15:30",
  },
  {
    class: "ppsr",
    day: "Saturday",
    startTime: "16:00",
    endTime: "17:00",
  },
  {
    class: "annie",
    day: "Saturday",
    startTime: "18:00",
    endTime: "22:00",
  },
  {
    class: "launge ball",
    day: "Sunday",
    startTime: "10:00",
    endTime: "13:30",
  },
  {
    class: "murph",
    day: "Sunday",
    startTime: "16:00",
    endTime: "20:00",
  },
  {
    class: "crossfit",
    day: "Sunday",
    startTime: "21:00",
    endTime: "23:00",
  },
];

export default data;
