const data = [
  {
    name: "crossfit",
    CoachName: "Adam Smith",
    day: "Monday",
    StartTime: "10:00",
    EndTime: "14:00",
  },
  {
    name: "launge ball",
    CoachName: "Adam Smith",
    day: "Monday",
    StartTime: "16:00",
    EndTime: "18:00",
  },
  {
    name: "walls",
    CoachName: "Adam Smith",
    day: "Monday",
    StartTime: "18:00",
    EndTime: "20:00",
  },
  {
    name: "launge ball",
    CoachName: "Adam Smith",
    day: "Monday",
    StartTime: "21:00",
    EndTime: "23:00",
  },
  {
    name: "launge ball",
    CoachName: "Adam Smith",
    day: "Tuesday",
    StartTime: "14:00",
    EndTime: "17:00",
  },
  {
    name: "ppsr",
    CoachName: "Adam Smith",
    day: "Tuesday",
    StartTime: "18:00",
    EndTime: "20:00",
  },
  {
    name: "walls",
    CoachName: "Adam Smith",
    day: "Tuesday",
    StartTime: "20:00",
    EndTime: "22:00",
  },
  {
    name: "crossfit",
    CoachName: "Adam Smith",
    day: "Wednesday",
    StartTime: "10:00",
    EndTime: "15:00",
  },
  {
    name: "candy",
    CoachName: "Adam Smith",
    day: "Wednesday",
    StartTime: "16:00",
    EndTime: "19:00",
  },
  {
    name: "walls",
    CoachName: "Adam Smith",
    day: "Wednesday",
    StartTime: "20:30",
    EndTime: "23:00",
  },
  {
    name: "crossfit",
    CoachName: "Adam Smith",
    day: "Thursday",
    StartTime: "14:00",
    EndTime: "17:00",
  },
  {
    name: "chelsea",
    CoachName: "Adam Smith",
    day: "Thursday",
    StartTime: "18:00",
    EndTime: "22:00",
  },
  {
    name: "chelsea",
    CoachName: "Adam Smith",
    day: "Thursday",
    StartTime: "18:00",
    EndTime: "22:00",
  },
  {
    name: "launge ball",
    CoachName: "Adam Smith",
    day: "Friday",
    StartTime: "10:00",
    EndTime: "13:00",
  },
  {
    name: "candy",
    CoachName: "Adam Smith",
    day: "Friday",
    StartTime: "16:00",
    EndTime: "19:00",
  },
  {
    name: "crossfit",
    CoachName: "Adam Smith",
    day: "Friday",
    StartTime: "22:00",
    EndTime: "23:00",
  },
  {
    name: "walls",
    CoachName: "Adam Smith",
    day: "Saturday",
    StartTime: "14:00",
    EndTime: "15:30",
  },
  {
    name: "ppsr",
    day: "Saturday",
    CoachName: "Adam Smith",
    StartTime: "16:00",
    EndTime: "17:00",
  },
  {
    name: "annie",
    CoachName: "Adam Smith",
    day: "Saturday",
    StartTime: "18:00",
    EndTime: "22:00",
  },
  {
    name: "launge ball",
    CoachName: "Adam Smith",
    day: "Sunday",
    StartTime: "10:00",
    EndTime: "13:30",
  },
  {
    name: "murph",
    CoachName: "Adam Smith",
    day: "Sunday",
    StartTime: "16:00",
    EndTime: "20:00",
  },
  {
    name: "crossfit",
    CoachName: "Adam Smith",
    day: "Sunday",
    StartTime: "21:00",
    EndTime: "23:00",
  },
];

export default data;
